### ISSUE TITLE
None of the codes work

### ISSUE THREAD

**Issue by DrawYourSwordRamza** [KunoichiZ/SoVUS-NTR-Plugin#11]
Tried it on a N2DS on BootNTR 3.2, 3,3, and 3.6. Infinite HP crashes the game, and the others flat-out don't work. I tested Instant Support Conversations, Infinite Movement, Infinite HP, and Set Starting Position Anywhere. I know I'm using the US version of the game, so what the hell is wrong with the cheats?

**Comment by KunoichiZ** [comment]
Note I didn't make these cheats so you're preaching to the wrong choir. I just made the plugin. This plugin is also for v1.0, which means you cannot have the v1.1 update installed.

**Comment by saijm4444** [comment]
@DrawYourSwordRamza Multiple issues have been raised in the past to this effect, and it was also determined that the update breaks the cheats. Do your research next time please.

**Comment by KunoichiZ** [comment]
Exactly. I even said in the README that the update broke the plugin. Read next time before posting an issue please.
