### ISSUE TITLE
All stats by level up stays enabled even when turned off in plugin menu

### ISSUE THREAD

**Issue by JeanpiASDF** [KunoichiZ/SoVUS-NTR-Plugin#2]
Enabling the all stats by level up plugin makes it stay enabled even when turned off in the plugin menu. To turn it off again you have to restart your 3DS for stats growths to go back to normal, which if I remember correctly wasn't the case in the Fates plugin. It should be somewhat like the XP pluging where you enable it and disable it by inputing certain buttons (start up to enable+ start down to disable) for convenience.

**Comment by KunoichiZ** [comment]
I have no control over the cheats. You are asking the wrong person. I only made the plugin.
