### ISSUE TITLE
Plugin doesn't work post game update

### ISSUE THREAD

**Issue by saijm4444** [KunoichiZ/SoVUS-NTR-Plugin#6]
I don't know if it is the game update or the latest dlc that causes it, but the game crashes past the "Loading extra data" box, when the plugin is running in the background.
![img_20170623_204256](https://user-images.githubusercontent.com/19181271/27488735-bb1c14c8-5855-11e7-8a1d-2a2815cb6716.jpg)
[crash_dump_00000005.zip](https://github.com/KunoichiZ/SoVUS-NTR-Plugin/files/1098291/crash_dump_00000005.zip)
Rename the .zip to .dmp

**Comment by SkyOc1** [comment]
It didn't crash for me, but it no longer works (or at the very least on dlc characters.).

**Comment by saijm4444** [comment]
Tried without the DLC, and still didn't work. I am now sure it doesn't work due to the game being updated recently.
