### ISSUE TITLE
"Get 100 Exp After Battling Enemy" cheat not working

### ISSUE THREAD

**Issue by 0klux** [KunoichiZ/SoVUS-NTR-Plugin#7]
It only gives 100 RES to every ally and enemy but there isn't any increase on XP gain.

**Comment by g3arIV** [comment]
It works perfectly for me. Try turning the cheat on before going into battle. If that doesn't work, turn it off, then jump into battle, then turn it on. The next battle should enable the cheat. This always works for me when I get that issue.
